--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/alex/Pictures/Wallpapers/lain_cross.jpeg"

-- Special
background="#000000"
foreground="#e8bac2"
cursor="#e8bac2"

-- Colors
color0="#000000"
color1="#A05969"
color2="#C16B7E"
color3="#BD7A80"
color4="#CE7688"
color5="#BE8F86"
color6="#CC8F8D"
color7="#e8bac2"
color8="#a28287"
color9="#A05969"
color10="#C16B7E"
color11="#BD7A80"
color12="#CE7688"
color13="#BE8F86"
color14="#CC8F8D"
color15="#e8bac2"
