# Shell variables
# Generated by 'wal'
wallpaper='/home/alex/Pictures/Wallpapers/lain_cross.jpeg'

# Special
background='#000000'
foreground='#e8bac2'
cursor='#e8bac2'

# Colors
color0='#000000'
color1='#A05969'
color2='#C16B7E'
color3='#BD7A80'
color4='#CE7688'
color5='#BE8F86'
color6='#CC8F8D'
color7='#e8bac2'
color8='#a28287'
color9='#A05969'
color10='#C16B7E'
color11='#BD7A80'
color12='#CE7688'
color13='#BE8F86'
color14='#CC8F8D'
color15='#e8bac2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
